server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/filme?createDatabaseIfNotExist=true
    url: ${JDBC_DATASOURCE_URL}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update